[".agents/skills/grill-me/SKILL.md"]
type = "file"
url = "https://raw.githubusercontent.com/mattpocock/skills/b8be62ffacb0118fa3eaa29a0923c87c8c11985c/skills/productivity/grill-me/SKILL.md"

[".agents/skills/handoff/SKILL.md"]
type = "file"
url = "https://raw.githubusercontent.com/mattpocock/skills/b8be62ffacb0118fa3eaa29a0923c87c8c11985c/skills/productivity/handoff/SKILL.md"

[".agents/skills/write-a-skill/SKILL.md"]
type = "file"
url = "https://raw.githubusercontent.com/mattpocock/skills/b8be62ffacb0118fa3eaa29a0923c87c8c11985c/skills/productivity/write-a-skill/SKILL.md"
