# Alacritty Configuration File
# 詳細は https://alacritty.org/config-alacritty.html を参照

[window]
# 起動時のウィンドウサイズ (カラム数, 行数)
dimensions = { columns = 120, lines = 40 }

[font]
# 使用するフォントファミリー
normal = { family = "BIZ UDゴシック", style = "Regular" }